<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Klooz3-e515e851-e4a2-4e41-a830-1b6f7e434fc4</UserSecretsId>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.23">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.16" />
    <PackageReference Include="SendGrid" Version="9.28.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.0" />
  </ItemGroup>

</Project>
